//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PhotoID.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW                    101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PhotoIDTYPE                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_FORMVIEWFILE                310
#define IDB_BITMAP_FITFACE              311
#define IDB_BITMAP_CROP                 312
#define IDB_BITMAP_STAMP                313
#define IDB_BITMAP_BLUR                 314
#define IDB_BITMAP_PRINT                315
#define IDD_DIALOG1                     316
#define IDB_BITMAP_UNDO                 317
#define IDB_BITMAP_SAVE                 319
#define IDB_BITMAP_ADMIN                320
#define IDB_BITMAP_REFRESH              322
#define IDD_DILG_LOG                    323
#define IDD_DLG_PASS                    324
#define IDD_DLG_RESET_PASS              325
#define IDB_BITMAP_COLORBAL             326
#define IDB_BITMAP1                     327
#define IDB_BITMAP_REMOVE_HL            327
#define IDC_SLIDER_ROTATE               1000
#define IDC_SLIDER_BRINGTNESS           1001
#define IDC_EDIT_ROT_VALUE              1002
#define IDC_BN_AUTOFIT                  1003
#define IDC_SLIDER_CONTRAST             1005
#define IDC_SLIDER_CURSOR_SIZE          1006
#define IDC_BN_PRINT                    1007
#define IDC_BN_CROPIMG                  1008
#define IDC_BN_STEMP                    1009
#define IDC_BN_STEMP2                   1010
#define IDC_COMBO1                      1011
#define IDC_BN_UNDO                     1012
#define IDC_SPIN2                       1020
#define IDC_EDIT_TOP_MARGIN             1021
#define IDC_SPIN3                       1022
#define IDC_EDIT_BOT_MARGIN             1023
#define IDC_PREVIEW                     1028
#define IDC_BN_SAVECROP                 1029
#define IDC_BN_ADMIN                    1030
#define IDC_EDIT_SAVE_PATH              1031
#define IDC_BN_PATH                     1032
#define IDC_EDIT2                       1033
#define IDC_EDIT_SAVE_WIDTH             1034
#define IDC_EDIT_SAVE_HEIGHT            1035
#define IDD_DLG_SAVEIMG                 1035
#define IDC_COMBO_IMGFORMAT             1036
#define IDC_BN_REFRESH                  1037
#define IDC_EDIT_PASS                   1040
#define IDC_BN_RESET_PASS               1041
#define IDC_EDIT_CURR_PASS              1042
#define IDC_EDIT_NEW_PASS               1043
#define IDC_LIST1                       1043
#define IDC_COMBO_MONTH                 1044
#define IDC_BN_SEARCH_LOG               1045
#define IDC_COMBO_YEAR                  1046
#define IDC_BN_CB                       1047
#define IDC_BUTTON1                     1048
#define IDC_BN_REOMVE_HL                1048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
